services:
  vulnerable-supply-chain:
    build: ./vulnerable
    container_name: vulnerable-supply-chain
    ports:
      - "5005:5000"

  secure-supply-chain:
    build: ./secure
    container_name: secure-supply-chain
    ports:
      - "5006:5000"
