services:
  vulnerable-injection:
    build: ./vulnerable
    container_name: vulnerable-injection
    ports:
      - "5001:5000"
    restart: unless-stopped

  secure-injection:
    build: ./secure
    container_name: secure-injection
    ports:
      - "5002:5000"
    restart: unless-stopped
