services:
  vulnerable-injection:
    build: ./vulnerable
    container_name: vulnerable-injection
    ports:
      - "5009:5000"
    restart: unless-stopped

  secure-injection:
    build: ./secure
    container_name: secure-injection
    ports:
      - "5010:5000"
    restart: unless-stopped
