services:
  vulnerable-crypto:
    build: ./vulnerable
    container_name: vulnerable-crypto
    ports:
      - "5007:5000"

  secure-crypto:
    build: ./secure
    container_name: secure-crypto
    ports:
      - "5008:5000"
