services:
  vulnerable-api-advanced:
    build: ./vulnerable
    container_name: vulnerable-api-advanced
    ports:
      - "5016:5000"

  secure-api-advanced:
    build: ./secure
    container_name: secure-api-advanced
    ports:
      - "5017:5000"
