services:
  vulnerable-broken-access:
    build: ./vulnerable
    container_name: vulnerable-broken-access
    ports:
      - "5003:5000"

  secure-broken-access:
    build: ./secure
    container_name: secure-broken-access
    ports:
      - "5004:5000"
