services:
  vulnerable-misconfig:
    build: ./vulnerable
    container_name: vulnerable-misconfig
    ports:
      - "5003:5000"

  secure-misconfig:
    build: ./secure
    container_name: secure-misconfig
    ports:
      - "5004:5000"
