services:
  vulnerable-auth:
    build: ./vulnerable
    container_name: vulnerable-auth
    ports:
      - "5014:5000"

  secure-auth:
    build: ./secure
    container_name: secure-auth
    ports:
      - "5015:5000"
